(function() {var implementors = {};
implementors["tsukuyomi_router"] = [{text:"impl&lt;T&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> for <a class=\"struct\" href=\"tsukuyomi_router/struct.Endpoint.html\" title=\"struct tsukuyomi_router::Endpoint\">Endpoint</a>&lt;T&gt; <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;T: <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a>,&nbsp;</span>",synthetic:true,types:["tsukuyomi_router::endpoint::Endpoint"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> for <a class=\"struct\" href=\"tsukuyomi_router/struct.EndpointId.html\" title=\"struct tsukuyomi_router::EndpointId\">EndpointId</a>",synthetic:true,types:["tsukuyomi_router::endpoint::EndpointId"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> for <a class=\"struct\" href=\"tsukuyomi_router/struct.Error.html\" title=\"struct tsukuyomi_router::Error\">Error</a>",synthetic:true,types:["tsukuyomi_router::error::Error"]},{text:"impl&lt;'r&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> for <a class=\"struct\" href=\"tsukuyomi_router/struct.Params.html\" title=\"struct tsukuyomi_router::Params\">Params</a>&lt;'r&gt;",synthetic:true,types:["tsukuyomi_router::param::Params"]},{text:"impl&lt;'r, T&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> for <a class=\"struct\" href=\"tsukuyomi_router/struct.Recognize.html\" title=\"struct tsukuyomi_router::Recognize\">Recognize</a>&lt;'r, T&gt; <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;T: <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Sync.html\" title=\"trait core::marker::Sync\">Sync</a>,&nbsp;</span>",synthetic:true,types:["tsukuyomi_router::router::Recognize"]},{text:"impl&lt;T&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> for <a class=\"struct\" href=\"tsukuyomi_router/struct.Router.html\" title=\"struct tsukuyomi_router::Router\">Router</a>&lt;T&gt; <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;T: <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a>,&nbsp;</span>",synthetic:true,types:["tsukuyomi_router::router::Router"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
