(function() {var implementors = {};
implementors["tsukuyomi_router"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a> for <a class=\"struct\" href=\"tsukuyomi_router/struct.Error.html\" title=\"struct tsukuyomi_router::Error\">Error</a>",synthetic:false,types:["tsukuyomi_router::error::Error"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a> for <a class=\"struct\" href=\"tsukuyomi_router/struct.EndpointId.html\" title=\"struct tsukuyomi_router::EndpointId\">EndpointId</a>",synthetic:false,types:["tsukuyomi_router::endpoint::EndpointId"]},{text:"impl&lt;T:&nbsp;<a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a>&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a> for <a class=\"struct\" href=\"tsukuyomi_router/struct.Endpoint.html\" title=\"struct tsukuyomi_router::Endpoint\">Endpoint</a>&lt;T&gt;",synthetic:false,types:["tsukuyomi_router::endpoint::Endpoint"]},{text:"impl&lt;'r&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a> for <a class=\"struct\" href=\"tsukuyomi_router/struct.Params.html\" title=\"struct tsukuyomi_router::Params\">Params</a>&lt;'r&gt;",synthetic:false,types:["tsukuyomi_router::param::Params"]},{text:"impl&lt;T:&nbsp;<a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a>&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a> for <a class=\"struct\" href=\"tsukuyomi_router/struct.Router.html\" title=\"struct tsukuyomi_router::Router\">Router</a>&lt;T&gt;",synthetic:false,types:["tsukuyomi_router::router::Router"]},{text:"impl&lt;'r, T:&nbsp;<a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a>&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a> for <a class=\"struct\" href=\"tsukuyomi_router/struct.Recognize.html\" title=\"struct tsukuyomi_router::Recognize\">Recognize</a>&lt;'r, T&gt;",synthetic:false,types:["tsukuyomi_router::router::Recognize"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
